replicaCount: 1
namespace: dev

image:
  repository: nginx
  tag: latest
  pullPolicy: Always

deployment:

application:
  readinessInitialDelaySeconds: 60
  readinessPeriodSeconds: 60
  timeoutSeconds: 60
  healthCheck: /actuator/health
  containerPort: 8080
  type: "spring"
  env:
    java_args: "--spring.cloud.config.uri=http://spring-cloud-config-server.default.svc.cluster.local --spring.profiles.active=sit --spring.cloud.config.fail-fast=true"
    java_opts: "-Duser.timezone=GMT+7"

service:
  type: ClusterIP
  port: 80
  internalPort: 80

ingress:
  host: coba.api.dev.pakaiwa.my.id

hpa:
  maxReplicas: 1
  minReplicas: 1
  targetCPUUtilizationPercentage: 70

resources:
  limits:
    cpu: 512m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi
